### PR TITLE
Catch all exceptions in SystemInfo

### PR DESCRIPTION
**Pull request by HengYeDev**
Logging  of system information isn't a critical process, we can just catch all the exceptions and log them.

### CODE REVIEW

**Comment by HengYeDev** [comment]
@perpetualKid Will the CI in this PR build packages for me to test?

**Comment by HengYeDev** [comment]
The reason of this change is that exceptions like this happen in Linux:

```
Error: System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Management.ManagementObject.GetRelated(String relatedClass, String relationshipClass, String relationshipQualifier, String relatedQualifier, String relatedRole, String thisRole, Boolean classDefinitionsOnly, EnumerationOptions options)
   at System.Management.ManagementObject.GetRelated(String relatedClass)
   at Orts.Common.Info.SystemInfo.GetPnPDeviceDrivers(ManagementObject device) in D:\a\1\s\Source\Orts.Common\Info\SystemInfo.cs:line 155
   at Orts.Common.Info.SystemInfo.WriteEnvironment(StringBuilder output) in D:\a\1\s\Source\Orts.Common\Info\SystemInfo.cs:line 91
   at Orts.Common.Info.SystemInfo.WriteSystemDetails() in D:\a\1\s\Source\Orts.Common\Info\SystemInfo.cs:line 42
   at Orts.Common.Logging.LoggingUtil.InitLogging(String logFileName, Boolean errorsOnly, Boolean appendLog) in D:\a\1\s\Source\Orts.Common\Logging\LoggingUtil.cs:line 93
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.InitLogging(Boolean appendLog) in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\GameStateRunActivity.cs:line 677
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass27_0.<Load>b__0() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\GameStateRunActivity.cs:line 159
   at Orts.ActivityRunner.Viewer3D.Processes.GameStateRunActivity.Load() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\GameStateRunActivity.cs:line 202
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.Load() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\LoaderProcess.cs:line 160
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.DoLoad() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\LoaderProcess.cs:line 139
   at Orts.ActivityRunner.Viewer3D.Processes.LoaderProcess.LoaderThread() in D:\a\1\s\Source\ActivityRunner\Viewer3D\Processes\LoaderProcess.cs:line 111
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

They can be caught in SystemInfo.

**Comment by perpetualKid** [comment]
there is another reference to WMI in ActivityRunner/Viewer3D/Viewer.cs which may need to be be covered: 
https://github.com/perpetualKid/ORTS-MG/blob/3de875e79d0d714db3e2a4c0e61d2673ac74ff01/Source/ActivityRunner/Viewer3D/Viewer.cs#L687

since you worked on master branch, the build went into the RC channel https://dev.azure.com/perpetualKid/ORTS-MG/_build/results?buildId=828&view=results, you can find your package appropriately here https://ultimaterails.blob.core.windows.net/builds/1.3.6/rc/1.3.6-rc.0.zip

I think I need to rework some of the build and channel alignment...

**Comment by HengYeDev** [comment]
@perpetualKid do you think I should merge into the monogame branch?

**Comment by perpetualKid** [comment]
> @perpetualKid do you think I should merge into the monogame branch?

@HengYeDev  thats where I typically work, so things automatically build into the CI channel

**Comment by HengYeDev** [comment]
@perpetualKid So should I re-make the PR? or is this OK for now?

**Comment by HengYeDev** [comment]
btw the binaries aren't uploaded because
`References service endpoint. PRs from repository forks are not allowed to access secrets in the pipeline. For more information see https://go.microsoft.com/fwlink/?linkid=862029 `

**Comment by perpetualKid** [comment]
I'm ok with the changes, so I've merged which just triggered a new build which should be published fine, thanks both for the updates and also submitting the bugs (also those in the pipeline). If next time just work on the monogame branch, I have some work item to refactor the build pipeline and whole versioninig/update but that will take a little while, condering to move to GitHub Actions but needs some research and testing.

**Pull request merged**
