### PR TITLE
Update to upstream

### PR DESCRIPTION
**Pull request by nfsprodriver**
This is a retry of #8 and works for me now. It contains latest openrails/openrails commits. Please check...

### CODE REVIEW

**Comment by perpetualKid** [comment]
Looks good.
Please be aware that work on this fork is currently suspended, as all efforts are to bring the changes back to official OR over next couple weeks. Going forward, it may be recommended to contribute to official OR (https://github.com/openrails/openrails)

**Comment by nfsprodriver** [comment]
Ah okay, so the Monogamization of the official game is in progress?

**Comment by perpetualKid** [comment]
> Ah okay, so the Monogamization of the official game is in progress?

correct, and the push in current changes like language version and .NET framework upgrade are prerequisites to solve first

**Comment by nfsprodriver** [comment]
Nice, until this is finished, I'll try to keep ORTS-MG up to date ;)

**Pull request merged**
